name: Send Email Reminders

# Trigger this workflow automatically on a schedule or via manual dispatch
on:
  schedule:
    # This cron schedule runs every day at 09:00 UTC
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  send-email-reminders-job:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          # If you have a requirements.txt:
          # pip install -r requirements.txt
          # OR install directly:
          pip install python-dotenv

      - name: Run the Email Reminder Script
        # These environment variables are read from your Secrets
        env:
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          LANDLORD_EMAIL: ${{ secrets.LANDLORD_EMAIL }}
          TENANTS: ${{ secrets.TENANTS }}
        run: |
          # If the script is at the repository root:
          python send_email_reminders.py

          # If it's in a 'scripts' folder:
          # python scripts/send_email_reminders.py
